contracts:
  contract_addr: "0x70a0F165d6f8054d0d0CF8dFd4DD2005f0AF6B55" # need to fix
eth_client:
  chain_id: 9
  gas_price_factor: 1
  web3_url:
    - "http://127.0.0.1:8545"
eth_sender:
  sender:
    wait_confirmations: 1
    expected_wait_time_block: 30
    tx_poll_period: 3
    max_txs_in_flight: 3
    is_enabled: true
    operator_private_key: "0x27593fea79697e947890ecbecce7901b0008345e5d7259710d0dd5e500d040be"
    operator_commit_eth_addr: "0xde03a0B5963f75f1C8485B355fF6D30f3093BDE7"
  gas_price_limit:
    default: 400000000000
    update_interval: 150
    sample_interval: 15
    scale_factor: 1
eth_watch:
  confirmations_for_eth_event: 0
  eth_node_poll_interval: 300
